default:  fxctmp9_tmp\light_volumetrics_ps20b.inc shaders\fxc\light_volumetrics_ps20b.vcs fxctmp9_tmp\light_volumetrics_vs20.inc shaders\fxc\light_volumetrics_vs20.vcs

fxctmp9_tmp\light_volumetrics_ps20b.inc shaders\fxc\light_volumetrics_ps20b.vcs: light_volumetrics_ps20b.fxc common_fxc.h common_pragmas.h common_ps_fxc.h common_flashlight_fxc.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." light_volumetrics_ps20b.fxc-----light_volumetrics_ps20b
	echo light_volumetrics_ps20b.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

fxctmp9_tmp\light_volumetrics_vs20.inc shaders\fxc\light_volumetrics_vs20.vcs: light_volumetrics_vs20.fxc common_vs_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." light_volumetrics_vs20.fxc-----light_volumetrics_vs20
	echo light_volumetrics_vs20.fxc>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

